owner: getmateo
repo: upptime

sites:
  - name: Mateo App PROD
    url: https://app.getmateo.com
  - name: Mateo App DEV
    url: https://app.dev.getmateo.com
  - name: Mateo Web PROD
    url: https://www.hellomateo.de/

status-website:
  cname: status.getmateo.com
  logoUrl: https://raw.githubusercontent.com/getmateo/upptime/master/assets/mateo-logo.svg
  name: Mateo
  introTitle: Welcome to the Mateo uptime status dashboard!
  introMessage: This page collects the uptime status information for the critical pieces of our infrastructure.
  navbar:
    - title: Status
      href: /
